# kFold

In [5]:
import numpy as np
from sklearn.model_selection import KFold

In [2]:
rn = range(1,26)

In [6]:
kf5 = KFold(n_splits=5)
kf3 = KFold(n_splits=3)


In [7]:
for trian_index,test_index in kf3.split(rn):
    print(trian_index,test_index)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [0 1 2 3 4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 17 18 19 20 21 22 23 24] [ 9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [17 18 19 20 21 22 23 24]


In [9]:
#if we want values, not the index we use np.take method

for trian_index,test_index in kf3.split(rn):
    print(np.take(rn,trian_index),np.take(rn,test_index))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25] [1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 18 19 20 21 22 23 24 25] [10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] [18 19 20 21 22 23 24 25]


# StratifiedKFold

In [2]:
from sklearn.datasets import make_classification
from sklearn.model_selection import StratifiedKFold

In [3]:
X,y = make_classification(n_samples=1000,n_classes=2,weights=[0.99,0.01],flip_y=0,random_state=1)
kfold = StratifiedKFold(n_splits=5,shuffle= True , random_state=1)


In [8]:
for train_ix,test_ix in kfold.split(X,y):
    train_X,test_X = X[train_ix],X[test_ix]
    train_y,test_y = y[train_ix],y[test_ix]
    train_0,train_1 = len(train_y[train_y==0]),len(train_y[train_y==1])
    test_0,test_1   = len(test_y[test_y==0]),len(test_y[test_y==1])
    
    print('>Train: 0=%d, 1=%d, test: 0=%d,1=%d',  (train_0,train_1,test_0,test_1))

>Train: 0=%d, 1=%d, test: 0=%d,1=%d (792, 8, 198, 2)
>Train: 0=%d, 1=%d, test: 0=%d,1=%d (792, 8, 198, 2)
>Train: 0=%d, 1=%d, test: 0=%d,1=%d (792, 8, 198, 2)
>Train: 0=%d, 1=%d, test: 0=%d,1=%d (792, 8, 198, 2)
>Train: 0=%d, 1=%d, test: 0=%d,1=%d (792, 8, 198, 2)


**using train test split**

In [11]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [14]:
X,y = make_classification(n_samples=1000,n_classes=2,weights=[0.99,0.01],random_state=1)
trainX,testX,trainy,testy = train_test_split(X,y,test_size=0.5,random_state=2)

In [18]:
train_0,train_1 = len(trainy[trainy==0]),len(trainy[trainy==1])
test_0,test_1   = len(testy[testy==0]),len(testy[testy==1])
    
print('>Train: 0=%d, 1=%d, test: 0=%d,1=%d',  (train_0,train_1,test_0,test_1))

>Train: 0=%d, 1=%d, test: 0=%d,1=%d (496, 4, 489, 11)


# leave one out 

In [20]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

In [25]:
x = np.array([[1,2],[3,4]])
y =  np.array([1,2])
loo = LeaveOneOut()
loo.get_n_splits(x)

2

# Example

In [29]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

In [30]:
df = pd.read_csv('Iris.csv')

In [31]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [32]:
X = df[['SepalLengthCm','SepalWidthCm','PetalWidthCm']]
y = df['Species']

In [33]:
model = svm.SVC()
accuracy = cross_val_score(model,X,y,scoring = 'accuracy',cv=10)
print(accuracy)
print('Accuracy of model with cross validation is :',accuracy.mean()*100)

[0.93333333 0.93333333 1.         0.93333333 1.         0.93333333
 0.86666667 1.         1.         0.93333333]
Accuracy of model with cross validation is : 95.33333333333334
